# -*- coding: utf-8 -*-
"""Data Analytics Lab 10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E6Ffs1QGD2TGS15xxsUC1bSeCLHB7BPm
"""

import numpy as np

def prog():
  x2=int(input())
  y2=int(input())
  z2=int(input())
  x1=int(input())
  y1=int(input())
  z1=int(input())
  if x2>=x1 and y2>=y1 and z2>=z1 :
    print('Yes')
  else:
    print('NO')

a = np.array([[1, 1], [2, 3],[3,3],[3,4]])
np.unique(a)

str1='hello'
str2='hellos'
for i in str1:
  if i not in str2:
    print(i)
for i in str2:
  if i not in str1:
    print(i)



