# -*- coding: utf-8 -*-
"""Data Analytics Lab 9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1S6TQHaRc5pDBLX8pTUUOpT8He1OPjw10
"""

import matplotlib.pyplot as plt

import numpy as np

import pandas as pd

xpoints=np.array([0,6])
ypoints=np.array([0,250])
plt.plot(xpoints,ypoints)
plt.show()

xpoints=np.array([0,6])
ypoints=np.array([0,250])
plt.plot(xpoints,ypoints,'s')
plt.show()

xpoints=np.array([1,2,6,8])
ypoints=np.array([3,8,1,10])
plt.plot(xpoints,ypoints)
plt.xlabel('Harsh')
plt.ylabel('Pandit')
plt.title('H036')
plt.show()

plt.plot(ypoints)
plt.show()

plt.plot(ypoints,'*r')
plt.show()

plt.plot(ypoints,marker='s',ms=15,color='black')
plt.show()

plt.plot(ypoints,marker='s',ms=15,color='black',mec='blue')
plt.show()

plt.plot(ypoints,marker='s',ms=15,color='black',mfc='pink')
plt.show()

plt.plot(ypoints,marker='s',ms=15,color='black',mfc='pink',linestyle='dotted')
plt.show()

plt.plot(ypoints,marker='s',ms=15,color='black',mfc='pink',linestyle='dotted',linewidth=10)
plt.show()

xpoints=np.array([0,6])
ypoints=np.array([0,250])
plt.plot(xpoints)
plt.plot(ypoints)
plt.show()

xpoints=np.array([0,6,23,34,56,78])
ypoints=np.array([0,250,1,12,23,45])
plt.plot(xpoints)
plt.plot(ypoints)
plt.legend(['Harsh','Pandit'])
plt.show()

df=pd.DataFrame(np.random.rand(10,5),columns=['a','b','c','d','e'])
df.plot.box(grid='True')

import seaborn as sn

data= np.random.randint(low=1,high=100,size=(10,10))
print('The data to be plotted: /n')
print(data)

hm=sn.heatmap(data=data,cmap='Copper')

plt.show()

data= np.random.randint(low=1,high=100,size=(10,10))
print('The data to be plotted: /n')
print(data)

hm=sn.heatmap(data=data,cmap='copper')

plt.show()

