# -*- coding: utf-8 -*-
"""Data Analytics 12.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HHycopLMyhkeBfv5_cCeE0O2GBas_bpR
"""

import pandas as pd

temp=str(input(''))
if temp == 'b' or temp=='B':
  print('Battle Ship')
elif temp=='c' or temp=='C':
  print('Cruise')
elif temp == 'f' or temp == 'F':
  print('Frigate')

arr=[1,2,2,2,3,3,4]
print('Unique Elements are: {}'.format(set(arr)))

str1='Harsh'
str2='Harshf'
for i in str1:
  if i in str2:
    pass
  else:
    print('extra element in str2 is : {}'.format(i))

for i in str2:
  if i in str1:
    pass
  else:
    print('extra element in str1 is : {}'.format(i))

import numpy as np

arr=[[1,2,2],[2,3,1]]
arr1=np.array(arr)

arr1.reshape(1,-1)

arr1.max()

arr1.min()

arr1=np.array([[1,2],[3,4]])
arr2=np.array([[3,5],[8,9]])
np.intersect1d(arr1,arr2)

if len(arr1)==len(arr2):
  print('True')
else:
  print('False')

arr=np.array([[1,2,2],[2,3,1]])
re_arr=arr.reshape(1,-1)
print(re_arr)

from random import randrange

arr1=[]
for i in range(9):
  arr1.append(randrange(3,13))
re_arr=np.array(arr1)
re_arr=re_arr.reshape(3,3)
re_arr

tt=int(input())
for i in range (tt):
  x1=5
  y1=4
  z1=3
  x2=int(input())
  y2=int(input())
  z2=int(input())
  if x2>=x1 and z2<=z1 and y2>=y1:
    print('YES')
  else:
    print('NO')

