# -*- coding: utf-8 -*-
"""Data Analytics Lab 7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZYzDlst-ZJIkG8bnazPnFg38H5Cq63Ql
"""

import pandas as pd

import random
import numpy as np

df=pd.DataFrame(np.random.randn(5,3),index=['a','c','e','f','h'],columns=['one','two','three'])
df=df.reindex(['a','b','c','d','e','f','g','h'])
print(df)

print(df.isnull())

df=pd.DataFrame(np.random.randn(3,3),index=['a','e','c'],columns=['one','two','three'])
df=df.reindex(['a','b','c'])
print(df)
print('NaN replaced with 0 :')
print(df.fillna(0))

print(df.fillna(method='pad'))#

df= pd.DataFrame({'one':[10,20,30,40,50,2000],'two':[1000,0,30,40,50,60]})
print(df.replace({1000:10,2000:60}))

ipl_data={'Team':['r','r','d','d','k','k','k','r','ro','ro','r'],'Rank':[1,2,2,3,3,4,1,1,2,4,1,2]}
df=pd.dataframe(ipl_data)
grouped=df.groupby('Team')