# -*- coding: utf-8 -*-
"""Data Analytics Assignment 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tKKE3JhXG82FmzMk-nAhC7pYpoOX0KrM

Name : Harsh Pandit

Roll: H036

Stream:Mechatronics
"""

#Write a Python function that takes a sequence of numbers and determines whether all the numbers are different from each other.
seq=[1,2,3,4,51,1]
seq_set=list(set(seq))
if seq == seq_set:
  print('Distinct values present')
else:
  print('No distinct values')

#Write a Python program to convert integer to string and to convert string to integer.
string_input=str(input('Enter string input: '))
int_input=int(input('Enter string input: '))
conv_int=int(string_input)
conv_string=str(int_input)
print(type(conv_int))
print(type(conv_string))

#WAP to remove an element from the set.
def_set={1,2,3,4,5}
print('Set before deletion: {}'.format(def_set))
def_set.remove(5)
print('Set after deletion: {}'.format(def_set))

#Write a Python program to check a given list of integers where the sum of the first i integers is i.
int_list=[0,0,3,4,5,6,7,8]
temp=0
sum=0
while temp ==0 :
  i=int(input('Enter the number of terms: '))
  if i < len(int_list):
    temp =1
  else :
    print('Given input exceeded limits')
    i=int(input('Enter the number of terms: '))
    temp=0
for n in range (i):
  sum=sum+int_list[n]
if sum==int_list[i-1]:
  print('Sum of the first i integers is i')
else:
  print('Sum of the first i integers is not i')

#Write a Python program to unpack a tuple in several variables
tup=(1,2,3,4)
(a,b,c,d)=tup
print(a)
print(b)
print(c)
print(d)

#WAP to check the set is the subset of another set.
subset={1,2,3,4,321}
check_set={1,2,3,4,5,6,7,8}
intersetion_set=check_set.intersection(subset)
if subset == intersetion_set:
  print('Is a subset')
else:
  print('Not a subset')

#WAP to check that tuple has a distinct element of not.
tup=(1,2,3,4,5,6,7,1)
set_to_tup=tuple(set(tup))
if tup==set_to_tup:
  print('Distinct values present')
else:
    print('No distinct values')

#Write a python program to Check if the given element is present in tuple or not.
tup=(1,2,3,4,5,6,7,1)
i=int(input('Enter element: '))
if i in tup:
  print('Element present')
else:
  print('Element not present')

#Write a Python program to test if a variable is a list or tuple or a set
lst=[1,2,3]
list_lst=list(lst)
set_lst=set(lst)
tuple_lst=tuple(lst)
if type(lst)==type(tuple_lst):
  print('It is a tuple')
elif type(lst)==type(list_lst):
  print('It is a list')
elif type(lst)==type(set_lst):
  print('It is a set')
else:
  print('None')

#WAP to copy few elements from one set to another set
original_set={1,2,3,4}
added_set=original_set
print("Set before addition: {}".format(original_set))
add_set={5,6,7,8}
added_set.update(add_set)
print("Set after addition: {}".format(added_set))