# -*- coding: utf-8 -*-
"""Data Analytics Lab 4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LG4uhi0EWK0yLis8IQlRprP9qxGFhgbQ
"""

import numpy as np

arr=np.array((1,2,3,4,5))
print(arr)

print(arr.ndim)

arr=np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2,1])

x=arr.copy()
print(x)

x=arr.view()#in copy the copied array will not be affected incase original array is changed but in view it will change
arr[0,1]=123
print(x)

