# -*- coding: utf-8 -*-
"""Data Analytics Lab 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TBkFneFaZr2CfoVGiwYtnNOG95yznPQm
"""

string=str(input("Enter the string: "))
inv_string=string[::-1]
print('String is a palindrome') if string==inv_string else print('String is not a palindrome')

arr=[1,2,3,4,5,6,7,8]
print('Sum of an array is: ',sum(arr))

arr=[1,2,3,4,5,6,7,8]
print('maximum number in an array is: ',max(arr))

mlist=['a','b','c','o','k','m']
mlist[1:3]=['bl','w']
print(mlist)

mlist=['a','b','c','o','k','m']

lst=['dc','df']
mlist=['a','b','c','o','k','m']
mlist.extend(lst)
print(mlist)

mlist=['a','b','c','o','k','m']
mlist.insert(1,'harsh')
print(mlist)

