# -*- coding: utf-8 -*-
"""Data Analytics Lab 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VhngLvR2jcIbpuGFkuaLgJy49NxYnAIP
"""

number_of_terms=int(input('Enter the number of terms: '))
n=number_of_terms
sum=(n*(n+1)/2)**2
print('Sum of cube of numbers uptil {} is {}'.format(n,sum))

number=int(input('Enter the number : '))
temp=number
sum=0
while temp > 0:
  r=temp%10
  print(r)
  sum+=(r*r*r)
  temp=temp//10
print(sum)
if sum==number:
  print('It {} is an armstrong number'.format(number))
else:
  print('It {} is not an armstrong number'.format(number))

#swapping first and last elements in a list
lst=['a','b','c','d','e']
a=lst[0]
lst[0]=lst[len(lst)-1]
lst[len(lst)-1]=a
print(lst)

#seapping 2 elements in a list
a=int(input('Enter index number one to be swapped: '))
b=int(input('Enter index number two to be swapped: '))
lst=['a','b','c','d','e']
an=lst[a]
lst[a]=lst[b]
lst[b]=an
print(lst)

#finding length of list
lst=['a','b','c','d','e']
print('Length of list is: ',len(lst))

#finding a number in list
a=int(input('Enter number to be found: '))
lst=[1,2,3,4,5,6,7]
print('Number is in list') if a in lst else print('Number is not in list')

#reversing a list
lst=['a','b','c','d','e']
print(lst[::-1])

#finding sum of numbers in a list
lst=[1,2,3,4,5,6,7]
print(sum(lst))

#finding product of numbers in a list
lst=[1,2,3,4,5,6,7]
product=1
for i in lst:
  product*=i
print(product)

#smallest no in list
lst=[1,2,3,4,5,6,7]
print(min(lst))

#largest no in list
lst=[1,2,3,4,5,6,7]
print(max(lst))

#second largest no in list
lst=[1,2,3,4,5,6,7]
st=lst
st.sort()
print(st[1])

#nth largest no in list
n=int(input('Enter n: '))
lst=[1,2,3,4,5,6,7]
st=lst
st.sort()
print(st[n-1])

#even numbers in a list
lst=[1,2,3,4,5,6,7]
print('Even numbers are:')
for i in lst:
  if i%2==0:
    print(i)

#odd numbers in a list
lst=[1,2,3,4,5,6,7]
print('Odd numbers are:')
for i in lst:
  if i%2==0:
    pass
  else:
    print(i)

#positive numbers in a list
lst=[1,2,3,4,5,6,7]
print('Positive numbers are:')
for i in lst:
  if i>0:
    print(i)

#negative numbers in a list
lst=[1,2,3,4,5,6,7]
print('Negative numbers are:')
for i in lst:
  if i<0:
    print(i)

#positive numbers in a list
lst=[1,2,3,4,5,6,7]
f=int(input('Enter the start: '))
e=int(input('Enter the end: '))
print('Positive numbers are:')
for i in lst:
  if i>0 and i>f and i<e:
    print(i)

#negative numbers in a list
lst=[1,2,3,4,5,6,7]
f=int(input('Enter the start: '))
e=int(input('Enter the end: '))
print('negative numbers are:')
for i in lst:
  if i>0 and i>f and i<e:
    print(i)

st=str(input("Enter the string: "))
st1=st
for i in st:
  for j in st:
    if i==j:
      st1.replace(i,'',2)
print(st1)



